# Generated by Django 4.1.7 on 2023-04-08 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_category_announcement'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='announcement',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.RenameField(
            model_name='announcement',
            old_name='text',
            new_name='task',
        ),
    ]
