# Generated by Django 4.1.7 on 2023-04-10 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_announcement_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='time_create',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='announcement',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
