# Generated by Django 4.1.7 on 2023-04-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_announcement_photo_announcement_time_create_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
