# Generated by Django 4.1.7 on 2023-04-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_announcement_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='photo',
        ),
        migrations.AddField(
            model_name='announcement',
            name='img',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
