# Generated by Django 4.1.7 on 2023-04-14 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_remove_announcement_photo_announcement_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='announcement',
            name='img',
            field=models.ImageField(default='', null=True, upload_to='images'),
        ),
    ]
