# Generated by Django 4.1.7 on 2023-04-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_announcement_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='announcement',
            old_name='img',
            new_name='image',
        ),
    ]
